import './globals.css';
import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';

const relaway = Raleway({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Marcelo | Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className={relaway.className}>{children}</body>
    </html>
  );
}
