import Html from '../../public/icons/html-5.png';
import Javascript from '../../public/icons/js.png';
import React from '../../public/icons/react.png';
import Nextjs from '../../public/icons/nextjs.png';
import Git from '../../public/icons/git.png';
import TypeScript from '../../public/icons/typescript.svg';
import Css from '../../public/icons/css-3.png';
import Tailwind from '../../public/icons/tailwind.png';
import Shopify from '../../public/icons/shopify-t.webp';
import Hydrogen from '../../public/icons/hydrogen.svg';
import Ionic from '../../public/icons/ionic.svg';
import Liquid from '../../public/icons/liquid.svg';
import type { SkillItem } from '@/types/portfolio';
import type { Locale } from '@/i18n/LocaleProvider';

export function getSkillsData(locale: Locale): SkillItem[] {
  if (locale === 'en') {
    return [
      {
        id: 1,
        icon: Html,
        text: 'HTML',
        category: 'Web Fundamentals',
        level: 'Expert',
        experience: '4 years',
        description: 'I build semantic and accessible interfaces focused on SEO and scalability.',
        highlights: ['Semantics', 'Accessibility', 'Technical SEO'],
      },
      {
        id: 2,
        icon: Css,
        text: 'CSS',
        category: 'Web Fundamentals',
        level: 'Advanced',
        experience: '4 years',
        description: 'I design visual systems with clean style architecture and rendering performance.',
        highlights: ['Responsive layout', 'Animations', 'Design system'],
      },
      {
        id: 3,
        icon: Javascript,
        text: 'JavaScript',
        category: 'Language',
        level: 'Advanced',
        experience: '4 years',
        description: 'I deliver robust UI logic, integrations, and reliable state handling.',
        highlights: ['ESNext', 'DOM APIs', 'Async patterns'],
      },
      {
        id: 4,
        icon: Git,
        text: 'Git & GitHub',
        category: 'Tools',
        level: 'Advanced',
        experience: '4 years',
        description: 'I structure collaborative versioning workflows with safe delivery practices.',
        highlights: ['GitFlow', 'Code review', 'CI pipelines'],
      },
      {
        id: 5,
        icon: TypeScript,
        text: 'TypeScript',
        category: 'Language',
        level: 'Advanced',
        experience: '3 years',
        description: 'I use strong typing to reduce bugs and speed up front-end maintenance.',
        highlights: ['Practical types', 'Inference', 'Developer experience'],
      },
      {
        id: 6,
        icon: Tailwind,
        text: 'TailwindCSS',
        category: 'UI',
        level: 'Advanced',
        experience: '3 years',
        description: 'I build consistent interfaces with reusable tokens and components.',
        highlights: ['Utility-first', 'Themes', 'Scalability'],
      },
      {
        id: 7,
        icon: React,
        text: 'React',
        category: 'Framework',
        level: 'Advanced',
        experience: '3 years',
        description: 'I craft reactive interfaces with component composition and strong UX focus.',
        highlights: ['Hooks', 'Component architecture', 'Performance'],
      },
      {
        id: 8,
        icon: Nextjs,
        text: 'Next.js',
        category: 'Framework',
        level: 'Advanced',
        experience: '3 years',
        description: 'I build modern apps with SSR, SSG, and native performance features.',
        highlights: ['App Router', 'SSR/SSG', 'Image optimization'],
      },
      {
        id: 9,
        icon: Shopify,
        text: 'Shopify',
        category: 'E-commerce',
        level: 'Advanced',
        experience: '2 years',
        description: 'I work in Shopify ecosystem focused on conversion and shopping experience.',
        highlights: ['Custom themes', 'Storefront', 'Checkout UX'],
      },
      {
        id: 10,
        icon: Liquid,
        text: 'Liquid',
        category: 'E-commerce',
        level: 'Advanced',
        experience: '2 years',
        description: 'I customize Shopify templates with clean structure and performance mindset.',
        highlights: ['Templates', 'Sections', 'Snippets'],
      },
      {
        id: 11,
        icon: Hydrogen,
        text: 'Hydrogen',
        category: 'E-commerce',
        level: 'Intermediate',
        experience: '2 years',
        description: 'I build headless storefront experiences using modern stack patterns.',
        highlights: ['Headless', 'Storefront API', 'SSR'],
      },
      {
        id: 12,
        icon: Ionic,
        text: 'Ionic & Capacitor',
        category: 'Mobile',
        level: 'Advanced',
        experience: '3 years',
        description: 'I develop hybrid mobile experiences leveraging web stack and native deployment.',
        highlights: ['Hybrid apps', 'Capacitor plugins', 'Mobile UI'],
      },
    ];
  }

  return [
    {
      id: 1,
      icon: Html,
      text: 'HTML',
      category: 'Base Web',
      level: 'Especialista',
      experience: '4 anos',
      description: 'Estruturo interfaces semânticas e acessíveis para produtos com foco em SEO e escalabilidade.',
      highlights: ['Semântica', 'A11y', 'SEO técnico'],
    },
    {
      id: 2,
      icon: Css,
      text: 'CSS',
      category: 'Base Web',
      level: 'Avançado',
      experience: '4 anos',
      description: 'Crio sistemas visuais com arquitetura de estilos limpa e foco em performance de renderização.',
      highlights: ['Layout responsivo', 'Animations', 'Design System'],
    },
    {
      id: 3,
      icon: Javascript,
      text: 'JavaScript',
      category: 'Linguagem',
      level: 'Avançado',
      experience: '4 anos',
      description: 'Desenvolvo lógica robusta para UI, integrações e manipulação eficiente de estados.',
      highlights: ['ESNext', 'DOM APIs', 'Async patterns'],
    },
    {
      id: 4,
      icon: Git,
      text: 'Git e GitHub',
      category: 'Ferramentas',
      level: 'Avançado',
      experience: '4 anos',
      description: 'Organizo fluxos de versionamento para times com foco em colaboração e segurança de entrega.',
      highlights: ['GitFlow', 'Code review', 'CI pipelines'],
    },
    {
      id: 5,
      icon: TypeScript,
      text: 'TypeScript',
      category: 'Linguagem',
      level: 'Avançado',
      experience: '3 anos',
      description: 'Uso tipagem forte para reduzir bugs e acelerar manutenção de projetos frontend.',
      highlights: ['Types úteis', 'Inferência', 'DX'],
    },
    {
      id: 6,
      icon: Tailwind,
      text: 'TailwindCSS',
      category: 'UI',
      level: 'Avançado',
      experience: '3 anos',
      description: 'Monto interfaces consistentes com tokens e componentes reutilizáveis.',
      highlights: ['Utility-first', 'Temas', 'Escalabilidade'],
    },
    {
      id: 7,
      icon: React,
      text: 'React',
      category: 'Framework',
      level: 'Avançado',
      experience: '3 anos',
      description: 'Construo UIs reativas com composição de componentes e excelente experiência do usuário.',
      highlights: ['Hooks', 'Arquitetura de componentes', 'Performance'],
    },
    {
      id: 8,
      icon: Nextjs,
      text: 'Next.js',
      category: 'Framework',
      level: 'Avançado',
      experience: '3 anos',
      description: 'Desenvolvo aplicações modernas com SSR, SSG e otimizações nativas do ecossistema.',
      highlights: ['App Router', 'SSR/SSG', 'Otimização de imagens'],
    },
    {
      id: 9,
      icon: Shopify,
      text: 'Shopify',
      category: 'E-commerce',
      level: 'Avançado',
      experience: '2 anos',
      description: 'Atuo em ecossistema Shopify com foco em experiência de compra e conversão.',
      highlights: ['Tema customizado', 'Storefront', 'Checkout UX'],
    },
    {
      id: 10,
      icon: Liquid,
      text: 'Liquid',
      category: 'E-commerce',
      level: 'Avançado',
      experience: '2 anos',
      description: 'Customizo templates Shopify com organização e performance em mente.',
      highlights: ['Templates', 'Sections', 'Snippets'],
    },
    {
      id: 11,
      icon: Hydrogen,
      text: 'Hydrogen',
      category: 'E-commerce',
      level: 'Intermediário',
      experience: '2 anos',
      description: 'Exploro storefronts headless com stack moderna para experiências premium.',
      highlights: ['Headless', 'Storefront API', 'SSR'],
    },
    {
      id: 12,
      icon: Ionic,
      text: 'Ionic & Capacitor',
      category: 'Mobile',
      level: 'Avançado',
      experience: '3 anos',
      description: 'Crio experiências mobile híbridas aproveitando stack frontend e deploy multiplataforma.',
      highlights: ['Hybrid Apps', 'Capacitor plugins', 'UI mobile'],
    },
  ];
}
